name = "julia_docker_compose_template"
uuid = "4db1448c-e4c9-4442-8e69-4dd87194702d"
authors = ["Malte Boehm <boemalte@gmail.com>"]
version = "0.1.0"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1"