name: Create Archive
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    needs: Test Build the Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'julia-docker-template.zip'
        exclusions: '*.github*'
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "julia-docker-template.zip"
        token: ${{ secrets.GITHUB_TOKEN }}